FROM golang:1.26.5-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -tags="embed timetzdata" -o /embed-checksum ./cmd/embed-checksum && /embed-checksum
